# Generated by Django 3.0.3 on 2020-02-16 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('photo', models.ImageField(unique=True, upload_to='pictures')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True)),
                ('picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pictureapp.Picture')),
            ],
        ),
        migrations.CreateModel(
            name='PictureGroup',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pictureapp.Picture')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
