# Generated by Django 3.0.2 on 2020-02-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
