# Generated by Django 3.0.3 on 2020-02-16 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pictureapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picturegroup',
            name='picture',
        ),
        migrations.AddField(
            model_name='picture',
            name='picture_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pictureapp.PictureGroup'),
        ),
        migrations.CreateModel(
            name='PictureGroupUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pictureapp.PictureGroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
