# Generated by Django 3.0.3 on 2020-02-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureapp', '0002_auto_20200209_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='photo',
            field=models.ImageField(unique=True, upload_to='pictures'),
        ),
    ]
