# Generated by Django 3.0.3 on 2020-02-16 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictureapp', '0003_remove_picturegroup_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='picture',
            table='pic',
        ),
        migrations.AlterModelTable(
            name='picturegroup',
            table='pic_grp',
        ),
        migrations.AlterModelTable(
            name='picturegroupusers',
            table='pic_grp_user',
        ),
        migrations.AlterModelTable(
            name='request',
            table='request',
        ),
    ]
