# Generated by Django 3.0.3 on 2020-02-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictureapp', '0003_auto_20200209_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
